print("Bienvenido. Este es el conversor de unidades de longitud.")
CM = float(input("Ingrese, por favor, el número en centímetros (CM): "))
Mili = (CM*10)
Deci = (CM/10)
Deca = (CM/1000)
Hecto = (CM/10000)
Km = (CM/100000)
print("El valor en milímetros es: " , Mili)
print("El valor en decímetros es: " , Deci)
print("El valor en decámetros es: " , Deca)
print("El valor en hectómetros es: " , Hecto)
print("El valor en kilometros es: " , Km)